package com.massivecraft.factions.struct;

import com.massivecraft.factions.P;
import org.bukkit.command.CommandSender;

public enum Permission {
    MANAGE_SAFE_ZONE("managesafezone"),
    MANAGE_WAR_ZONE("managewarzone"),
    OWNERSHIP_BYPASS("ownershipbypass"),
    ADMIN("admin"),
    ADMIN_ANY("admin.any"),
    AHOME("ahome"),
    ANNOUNCE("announce"),
    AUTOCLAIM("autoclaim"),
    AUTO_LEAVE_BYPASS("autoleavebypass"),
    ACCESS("access"),
    BYPASS("bypass"),
    BAN("ban"),
    UNBAN("unban"),
    BANLIST("banlist"),
    CALCWEALTH("calcwealth"),
    CHAT("chat"),
    CHATSPY("chatspy"),
    CLAIM("claim"),
    CLAIM_LINE("claim.line"),
    CLAIM_RADIUS("claim.radius"),
    CLAIM_CHUNK("claim.chunk"),
    COLEADER("coleader"),
    CONFIG("config"),
    CORE("core"),
    CREATE("create"),
    CRYSTAL("crystal"),
    DEINVITE("deinvite"),
    DESCRIPTION("description"),
    DISBAND("disband"),
    DISBAND_ANY("disband.any"),
    HELP("help"),
    HOME("home"),
    INVITE("invite"),
    JOIN("join"),
    JOIN_ANY("join.any"),
    JOIN_OTHERS("join.others"),
    KICK("kick"),
    KICK_ANY("kick.any"),
    LEAVE("leave"),
    LIST("list"),
    LOCK("lock"),
    MAP("map"),
    MISSION("mission"),
    MOD("mod"),
    MOD_ANY("mod.any"),
    MODIFY_POWER("modifypower"),
    MONEY_BALANCE("money.balance"),
    MONEY_BALANCE_ANY("money.balance.any"),
    MONEY_DEPOSIT("money.deposit"),
    MONEY_WITHDRAW("money.withdraw"),
    MONEY_WITHDRAW_ANY("money.withdraw.any"),
    MONEY_F2F("money.f2f"),
    MONEY_F2P("money.f2p"),
    MONEY_P2F("money.p2f"),
    MONITOR_LOGINS("monitorlogins"),
    NO_BOOM("noboom"),
    OPEN("open"),
    OWNER("owner"),
    OWNERLIST("ownerlist"),
    SET_PEACEFUL("setpeaceful"),
    SET_PERMANENT("setpermanent"),
    SET_PERMANENTPOWER("setpermanentpower"),
    SHIELD("shield"),
    SHOW_INVITES("showinvites"),
    PERM("perm"),
    POINTS("points"),
    POWERBOOST("powerboost"),
    POWER("power"),
    POWER_ANY("power.any"),
    RELATION("relation"),
    RELOAD("reload"),
    RULE("rules"),
    SAVE("save"),
    SETHOME("sethome"),
    SETHOME_ANY("sethome.any"),
    SETPOINTS("setpoints"),
    SETTOKENS("settokens"),
    SHOW("show"),
    STATS("stats"),
    STATUS("status"),
    STEALTH("stealth"),
    STUCK("stuck"),
    TAG("tag"),
    TITLE("title"),
    TOKENS("tokens"),
    TOGGLE_ALLIANCE_CHAT("togglealliancechat"),
    TOGGLE_TRUCE_CHAT("toggletrucechat"),
    TNT("tnt"),
    TNTCHEST("tntchest"),
    UNCLAIM("unclaim"),
    UNCLAIM_ALL("unclaimall"),
    UNCLAIM_CHUNK("unclaim.chunk"),
    VERSION("version"),
    SCOREBOARD("scoreboard"),
    SEECHUNK("seechunk"),
    SETWARP("setwarp"),
    TOP("top"),
    VAULT("vault"),
    SETMAXVAULTS("setmaxvaults"),
    WARP("warp"),
    WEALTH("wealth");

    public final String node;

    Permission(final String node) {
        this.node = "factions." + node;
    }

    public boolean has(CommandSender sender, boolean informSenderIfNot) {
        return P.p.perm.has(sender, this.node, informSenderIfNot);
    }

    public boolean has(CommandSender sender) {
        return has(sender, false);
    }
}